version: '3.8'

services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "8800:8800"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app
      - /app/node_modules
    command: yarn start

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: